FROM mcr.microsoft.com/windows/servercore:ltsc2019

LABEL maintainer "Marcin Mikołajczak"

# Download Links:
ENV sql_express_download_url "https://go.microsoft.com/fwlink/?linkid=866658"

ENV sa_password="_" \
    attach_dbs="[]" \
    ACCEPT_EULA="_" \
    sa_password_path="C:\ProgramData\Docker\secrets\sa-password"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# make install files accessible
COPY start.ps1 /
WORKDIR 'C:\'

RUN New-Item -ItemType Directory 'C:\Downloads' | Out-Null ; \
		Invoke-WebRequest -Uri $env:sql_express_download_url -OutFile 'C:\Downloads\SQL2019-SSEI-Expr.exe' ; \
		Start-Process -Wait -FilePath 'C:\Downloads\SQL2019-SSEI-Expr.exe' -ArgumentList /Quiet, /Action=Download, '/MediaPath=C:\Downloads' ; \
		Start-Process -Wait -FilePath 'C:\Downloads\SQLEXPR_x64_ENU.exe' -ArgumentList /Q, /X ; \
		C:\SQLEXPR_x64_ENU\setup.exe /q /ACTION=Install /INSTANCENAME=SQLEXPRESS /FEATURES=SQLEngine /UPDATEENABLED=0 /SQLSVCACCOUNT='NT AUTHORITY\System' /SQLSYSADMINACCOUNTS='BUILTIN\ADMINISTRATORS' /TCPENABLED=1 /NPENABLED=0 /IACCEPTSQLSERVERLICENSETERMS ; \
        Remove-Item -Recurse -Force 'C:\Downloads', 'C:\SQLEXPR_x64_ENU'

RUN stop-service MSSQL`$SQLEXPRESS ; \
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql15.SQLEXPRESS\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpdynamicports -value '' ; \
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql15.SQLEXPRESS\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpport -value 1433 ; \
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql15.SQLEXPRESS\mssqlserver\' -name LoginMode -value 2 ;

CMD .\start -sa_password $env:sa_password -ACCEPT_EULA $env:ACCEPT_EULA -attach_dbs \"$env:attach_dbs\" -Verbose
